name: medicall
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  curved_labeled_navigation_bar: ^2.0.2
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.5
  flutter_speed_dial: ^7.0.0
  chat_bubbles: ^1.5.0
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  http: ^1.1.2
  url_launcher: ^6.2.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.10
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1

flutter_native_splash:
  background_image: assets/images/gradient.png
  image: assets/images/iconaLogo.png
  android: true
  ios: true
  web: false
  fullscreen: true

  android_12:
    image: assets/images/logoInteroSplash.png
    #image: assets/images/iconaLogo.png
    #branding: assets/images/scrittaLogo.png
    color: "#00204A"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages