name: medicall
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  curved_labeled_navigation_bar: ^2.0.2
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.5

flutter_native_splash:
  background_image: assets/images/gradient.png
  image: assets/images/iconaLogo.png
  android: true
  ios: true
  web: false
  fullscreen: true

  android_12:
    image: assets/images/logoInteroSplash.png
    #image: assets/images/iconaLogo.png
    #branding: assets/images/scrittaLogo.png
    color: "#00204A"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
